apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: {$PROJECT}
  name: new-build-from-yaml-cli
spec:
  runPolicy: Serial
  source:
    contextDir: /
    git:
      ref: 7.1.0.Beta
      uri: {$GIT_REPO}
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jboss-eap70-openshift:1.4
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: 8d1d7bbf3313324f
    type: GitHub
  - generic:
      secret: 2a20ab9ac1316fcf
    type: Generic
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
